Traceback (most recent call last):
  File "/Users/helmut/Code/oe-python-template-example/.nox/docs-3-13/bin/oe-python-template-example", line 4, in <module>
    from oe_python_template_example.cli import cli
  File "/Users/helmut/Code/oe-python-template-example/src/oe_python_template_example/__init__.py", line 8, in <module>
    from .models import Echo, Health, HealthStatus, Utterance
  File "/Users/helmut/Code/oe-python-template-example/src/oe_python_template_example/models.py", line 5, in <module>
    from pydantic import BaseModel, Field
  File "<frozen importlib._bootstrap>", line 1412, in _handle_fromlist
  File "/Users/helmut/Code/oe-python-template-example/.nox/docs-3-13/lib/python3.13/site-packages/pydantic/__init__.py", line 421, in __getattr__
    module = import_module(module_name, package=package)
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/helmut/Code/oe-python-template-example/.nox/docs-3-13/lib/python3.13/site-packages/pydantic/main.py", line 34, in <module>
    from ._internal import (
    ...<12 lines>...
    )
  File "/Users/helmut/Code/oe-python-template-example/.nox/docs-3-13/lib/python3.13/site-packages/pydantic/_internal/_generics.py", line 8, in <module>
    from contextvars import ContextVar
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/contextvars.py", line 1, in <module>
    from _contextvars import Context, ContextVar, Token, copy_context
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1322, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1262, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1559, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1533, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1666, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1621, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 859, in spec_from_file_location
  File "<frozen importlib._bootstrap_external>", line 190, in _path_abspath
KeyboardInterrupt
