name: "Publish Docker Image"

on:
  workflow_call:
    # No inputs needed at this time

jobs:
  docker_publish:
    runs-on: ubuntu-latest
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write

    env:
      DOCKER_IO_REGISTRY: docker.io
      DOCKER_IO_IMAGE_NAME_ALL: helmuthva/oe-python-template-example
      DOCKER_IO_IMAGE_NAME_SLIM: helmuthva/oe-python-template-example-slim

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install dev tools
        shell: bash
        run: .github/workflows/_install_dev_tools.bash

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0


      - name: Log in to Docker Hub
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          username: ${{ secrets.DOCKER_IO_USERNAME }}
          password: ${{ secrets.DOCKER_IO_PASSWORD }}


      - name: Log in to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@38b8a86137171c128513e9be0b97bc476fbffcb5 # v5.6.0
        with:
          images: |
            ghcr.io/helmut-hoffer-von-ankershoffen/oe-python-template-example

            ${{ env.DOCKER_IO_IMAGE_NAME_ALL }}

          flavor: |
            latest=auto
            prefix=
            suffix=
          tags: |
            type=semver,pattern=v
            type=semver,pattern=v.
            type=semver,pattern=v

      - name: Build and push Docker image (all)
        uses: docker/build-push-action@e6ef1f314e8a75f35e85dbd71ebe08d4b3005fc8 # v6.2.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          target: all
          provenance: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Docker image (slim)
        uses: docker/build-push-action@e6ef1f314e8a75f35e85dbd71ebe08d4b3005fc8 # v6.2.0
        with:
          context: .
          push: true
          tags: |
            ghcr.io/helmut-hoffer-von-ankershoffen/oe-python-template-example-slim:latest
            ghcr.io/helmut-hoffer-von-ankershoffen/oe-python-template-example-slim:${{ github.ref_name }}

            ${{ env.DOCKER_IO_IMAGE_NAME_SLIM }}:latest
            ${{ env.DOCKER_IO_IMAGE_NAME_SLIM }}:${{ github.ref_name }}

          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          target: slim
          provenance: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
