name: "Vercel Preview Deployment"

on:
  workflow_call:
    # No inputs needed at this time

jobs:
  deploy-preview:
    if: (!contains(github.event.head_commit.message, '[skip ci]'))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      id-token: write  
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install uv
        uses: astral-sh/setup-uv@f94ec6bedd8674c4426838e6b50417d36b6ab231 # v5.3.1
        with:
          version: "0.6.3"
          enable-cache: true
          cache-dependency-glob: uv.lock

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Make Vercel distribution
        run: make dist_vercel

      - name: Deploy to Vercel
        id: deploy-vercel
        uses: helmut-hoffer-von-ankershoffen/vercel-deploy@6b4d15b80083745c218b5b8203077d5dd2de9f98
        with:
          GITHUB_DEPLOYMENT_ENV: Preview
          PRODUCTION: false
          WORKING_DIRECTORY: dist_vercel
          ARCHIVE: true
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Smoke Test of Vercel Deployment
        run: |
          response=$(curl -s -m 5 -H "x-vercel-protection-bypass: ${{ secrets.VERCEL_AUTOMATION_BYPASS_SECRET }}" ${{ steps.deploy-vercel.outputs.PREVIEW_URL }}/api/v2/hello/world)
          echo "API Response: $response"
          if [[ "$response" == *"Hello, world!"* ]]; then
            echo "✅ API response contains 'Hello, world!' as expected"
          else
            echo "❌ API response does not contain 'Hello, world!'"
            exit 1
          fi
