name: "Build and publish Docker image to docker.io and ghcr.io"

on:
  push:
    tags:
      - "v*.*.*"


env:
  DOCKER_IO_REGISTRY: docker.io
  DOCKER_IO_IMAGE_NAME_ALL: helmuthva/oe-python-template-example
  DOCKER_IO_IMAGE_NAME_SLIM: helmuthva/oe-python-template-example-slim


jobs:
  docker_image_build_publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install dev tools
        shell: bash
        run: .github/workflows/install_dev_tools.bash

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0


      - name: Log in to Docker Hub
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:

          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}



      - name: Log in to GitHub container registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io

          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: "(all target): Extract metadata (tags, labels) for Docker"
        id: meta-all
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
        with:


          images: |
            ${{ env.DOCKER_IO_IMAGE_NAME_ALL }}
            ghcr.io/${{ github.repository }}



          tags: |
            # set latest tag for releases
            type=raw,value=latest
            # set semver tags from git tags (v1.2.3 -> 1.2.3, 1.2, 1)
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}


      - name: "(slim target): Extract metadata (tags, labels) for Docker"
        id: meta-slim
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
        with:


          images: |
            ${{ env.DOCKER_IO_IMAGE_NAME_SLIM }}
            ghcr.io/${{ github.repository }}-slim



          tags: |
            # set latest tag for releases
            type=raw,value=latest
            # set semver tags from git tags (v1.2.3 -> 1.2.3, 1.2, 1)
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}



      - name: "(all target): Build and push Docker image"
        id: build-and-push-all
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        with:
          context: .
          file: ./Dockerfile
          target: all
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta-all.outputs.tags }}
          labels: ${{ steps.meta-all.outputs.labels }}



      - name: "(slim target): Build and push Docker image"
        id: build-and-push-slim
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        with:
          context: .
          file: ./Dockerfile
          target: slim
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta-slim.outputs.tags }}
          labels: ${{ steps.meta-slim.outputs.labels }}





      - name: "(all target): Generate artifact attestation"
        uses: actions/attest-build-provenance@c074443f1aee8d4aeeae555aebba3282517141b2 # v2.2.3
        with:
          subject-name: ${{ env.DOCKER_IO_REGISTRY }}/${{ env.DOCKER_IO_IMAGE_NAME_ALL }}
          subject-digest: ${{ steps.build-and-push-all.outputs.digest }}
          push-to-registry: true




      - name: "(slim target): Generate artifact attestation"
        uses: actions/attest-build-provenance@c074443f1aee8d4aeeae555aebba3282517141b2 # v2.2.3
        with:
          subject-name: ${{ env.DOCKER_IO_REGISTRY }}/${{ env.DOCKER_IO_IMAGE_NAME_SLIM }}
          subject-digest: ${{ steps.build-and-push-slim.outputs.digest }}
          push-to-registry: true
